create database biblioteca
use database biblioteca

-- MySQL Script generated by MySQL Workbench
-- Tue Aug 16 11:10:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`autores` (
  `idAutores` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `img` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAutores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`leitores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`leitores` (
  `idLeitores` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `idade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLeitores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`livros` (
  `idLivros` INT NOT NULL AUTO_INCREMENT,
  `autor` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `prazo` VARCHAR(45) NULL,
  `capa` VARCHAR(45) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `autores_idAutores` INT NOT NULL,
  `leitores_idLeitores` INT NOT NULL,
  PRIMARY KEY (`idLivros`, `autores_idAutores`),
  INDEX `fk_livros_autores1_idx` (`autores_idAutores` ASC) VISIBLE,
  INDEX `fk_livros_leitores1_idx` (`leitores_idLeitores` ASC) VISIBLE,
  CONSTRAINT `fk_livros_autores1`
    FOREIGN KEY (`autores_idAutores`)
    REFERENCES `biblioteca`.`autores` (`idAutores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livros_leitores1`
    FOREIGN KEY (`leitores_idLeitores`)
    REFERENCES `biblioteca`.`leitores` (`idLeitores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Biblioteca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Biblioteca` (
  `idBiblioteca` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `Livros_idLivros` INT NOT NULL,
  PRIMARY KEY (`idBiblioteca`),
  INDEX `fk_Biblioteca_Livros_idx` (`Livros_idLivros` ASC) VISIBLE,
  CONSTRAINT `fk_Biblioteca_Livros`
    FOREIGN KEY (`Livros_idLivros`)
    REFERENCES `biblioteca`.`livros` (`idLivros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
